Rate/config/routes.rb
Rails.application.routes.draw do
  resources :int_rates

end

Rate/app/models/int_rate.rb
require 'pry'

class IntRate < ActiveRecord::Base

  def pull_rates
    get_data = RestClient.get 'https://www.quandl.com/api/v3/datasets/FRED/DPRIME.json?api_key=yYkYRFD4ohRsNySjnXJT'
    api_rate_data = JSON.parse(get_data)['dataset']['data']
    interest_rates = api_rate_data.flatten
    binding.pry

  end

end

Rate/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rate/app/controllers/int_rates_controller.rb
class IntRatesController < ApplicationController


  before_action :set_int_rate, only: [:show, :edit, :update, :destroy]

  # GET /int_rates
  # GET /int_rates.json
  def index
    @int_rates = IntRate.all
  end

  # GET /int_rates/1
  # GET /int_rates/1.json
  def show
  end

  # GET /int_rates/new
  def new
    @int_rate = IntRate.new
  end

  # GET /int_rates/1/edit
  def edit
  end

  # POST /int_rates
  # POST /int_rates.json
  def create
    @int_rate = IntRate.new(int_rate_params)
    @int_rate.pull_rates

    respond_to do |format|
      if @int_rate.save
        format.html { redirect_to @int_rate, notice: 'Int rate was successfully created.' }
        format.json { render :show, status: :created, location: @int_rate }
      else
        format.html { render :new }
        format.json { render json: @int_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /int_rates/1
  # PATCH/PUT /int_rates/1.json
  def update
    respond_to do |format|
      if @int_rate.update(int_rate_params)
        format.html { redirect_to @int_rate, notice: 'Int rate was successfully updated.' }
        format.json { render :show, status: :ok, location: @int_rate }
      else
        format.html { render :edit }
        format.json { render json: @int_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /int_rates/1
  # DELETE /int_rates/1.json
  def destroy
    @int_rate.destroy
    respond_to do |format|
      format.html { redirect_to int_rates_url, notice: 'Int rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_int_rate
      @int_rate = IntRate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def int_rate_params
      params.require(:int_rate).permit(:InterestRate, :EffectiveDate, :CreationDate)
    end
end

Rate/app/helpers/application_helper.rb
module ApplicationHelper
end

Rate/app/helpers/int_rates_helper.rb
module IntRatesHelper
end

Rate/app/views/int_rates/_form.html.erb
<%= form_for(@int_rate) do |f| %>
  <% if @int_rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@int_rate.errors.count, "error") %> prohibited this int_rate from being saved:</h2>

      <ul>
      <% @int_rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :InterestRate %><br>
    <%= f.text_field :InterestRate %>
  </div>
  <div class="field">
    <%= f.label :EffectiveDate %><br>
    <%= f.date_select :EffectiveDate %>
  </div>
  <div class="field">
    <%= f.label :CreationDate %><br>
    <%= f.date_select :CreationDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rate/app/views/int_rates/edit.html.erb
<h1>Editing Int Rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @int_rate %> |
<%= link_to 'Back', int_rates_path %>

Rate/app/views/int_rates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Int Rates</h1>

<table>
  <thead>
    <tr>
      <th>Interestrate</th>
      <th>Effectivedate</th>
      <th>Creationdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @int_rates.each do |int_rate| %>
      <tr>
        <td><%= int_rate.InterestRate %></td>
        <td><%= int_rate.EffectiveDate %></td>
        <td><%= int_rate.CreationDate %></td>
        <td><%= link_to 'Show', int_rate %></td>
        <td><%= link_to 'Edit', edit_int_rate_path(int_rate) %></td>
        <td><%= link_to 'Destroy', int_rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Int rate', new_int_rate_path %>

Rate/app/views/int_rates/new.html.erb
<h1>New Int Rate</h1>

<%= render 'form' %>

<%= link_to 'Back', int_rates_path %>

Rate/app/views/int_rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Interestrate:</strong>
  <%= @int_rate.InterestRate %>
</p>

<p>
  <strong>Effectivedate:</strong>
  <%= @int_rate.EffectiveDate %>
</p>

<p>
  <strong>Creationdate:</strong>
  <%= @int_rate.CreationDate %>
</p>

<%= link_to 'Edit', edit_int_rate_path(@int_rate) %> |
<%= link_to 'Back', int_rates_path %>

Rate/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>